sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start Creating an image with dockerfile"
  - docker build -f docker/Dockerfile.dev ./ -t devsigner/docker-react-app

script:
  - docker run -e CI=true devsigner/docker-react-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-react-app"
  env: "Learndockerandcienv-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-740771697690"
  bucket_path: "docker-react-app"
  on:
    branch: master
access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_KEY

after_success:
  - echo "Test Success"
