version: "3"
services:
  react-app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - /usr/src/app/node_modules
      - ./:/usr/src/app
  tests:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/src/app/node_modules
      - ./:/usr/src/app
    command: [ "npm", "run", "test" ]