version: "3"
services:
  react-app:
    build:
      context: ../
      dockerfile: docker/Dockerfile.dev
    ports:
      - "8080:3000"
    volumes:
      - /usr/src/app/node_modules
      - ../:/usr/src/app
  tests:
    build:
      context: ../
      dockerfile: docker/Dockerfile.dev
    volumes:
      - /usr/src/app/node_modules
      - ../:/usr/src/app
    command: [ "npm", "run", "test" ]